// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWnhXUeyKx_U4heNLmmmfBQlFro0umShU',
    appId: '1:407083298479:web:580643af7c78fba77a6e5a',
    messagingSenderId: '407083298479',
    projectId: 'to-do-list-e9914',
    authDomain: 'to-do-list-e9914.firebaseapp.com',
    storageBucket: 'to-do-list-e9914.firebasestorage.app',
    measurementId: 'G-S3BXTJ6896',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnocAyRimsm3HY1EpnTW-lOg0aVkls_Gc',
    appId: '1:407083298479:android:3792911dd534df6b7a6e5a',
    messagingSenderId: '407083298479',
    projectId: 'to-do-list-e9914',
    storageBucket: 'to-do-list-e9914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPcO4R9TKtKgYh4Z6GYOjjcU8h-BI_lE',
    appId: '1:407083298479:ios:cb84feb70fa442b77a6e5a',
    messagingSenderId: '407083298479',
    projectId: 'to-do-list-e9914',
    storageBucket: 'to-do-list-e9914.firebasestorage.app',
    androidClientId: '407083298479-qk5smte0qcm3lrt298itpa0o520msdet.apps.googleusercontent.com',
    iosClientId: '407083298479-3dmrl9qpb8ase8ns2gc6cludoavi6rch.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARPcO4R9TKtKgYh4Z6GYOjjcU8h-BI_lE',
    appId: '1:407083298479:ios:cb84feb70fa442b77a6e5a',
    messagingSenderId: '407083298479',
    projectId: 'to-do-list-e9914',
    storageBucket: 'to-do-list-e9914.firebasestorage.app',
    androidClientId: '407083298479-qk5smte0qcm3lrt298itpa0o520msdet.apps.googleusercontent.com',
    iosClientId: '407083298479-3dmrl9qpb8ase8ns2gc6cludoavi6rch.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

}